### PR TITLE
Add additional settings and mappings for autocomplete for Ripple 2.0

### PR DESCRIPTION
**Pull request by krakerag**
These new settings and mappings attributes on the elasticsearch base index allow any app-search interfaces that use the index to perform autocomplete upon the 'title' and 'summary_processed' fields.

I have also updated the base images, the build steps and README to come into line with pygmyless/colima-based local build. If you have problems building another project, you can pull config from this branch (and develop once merged) to get other builds working.

### CODE REVIEW

**Comment by krakerag** [comment]
@mayurngondhkar I had to change the base composer.json to reference in order to get it to work with reference site for testing purposes - should I change it back to what develop has before we merge this?

**Comment by mayurngondhkar** [comment]
> @mayurngondhkar I had to change the base composer.json to reference in order to get it to work with reference site for testing purposes - should I change it back to what develop has before we merge this?

Hey @krakerag , it has to be changed back before it's merged

**Comment by krakerag** [comment]
@mayurngondhkar updated, can you review please?

**Comment by mayurngondhkar** [comment]
> @mayurngondhkar updated, can you review please?

@krakerag the `composer.json` LGTM

**Comment by krakerag** [comment]
> > @mayurngondhkar updated, can you review please?
> 
> @krakerag the `composer.json` LGTM

Approve the PR for me please so I can merge when we're ready to get develop -> reference branch :)

**Pull request merged**
